name: Auto-translate JSON

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'locales/en.json'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Translate en.json -> sv-SE.json (only changed keys)
        env:
          SOURCE_JSON: locales/en.json
          TARGET_JSON: locales/sv-SE.json
          SOURCE_LANG: en-GB
          TARGET_LANG: sv-SE
          STRIP_QUOTES: "true"
          # Optional: custom cache path per locale
          # I18N_CACHE: locales/.i18n-cache.sv-SE.json
        run: node scripts/translate-json.js

      - name: Commit changes (if any)
        if: github.ref == 'refs/heads/main'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add locales/sv-SE.json locales/.i18n-cache*.json
            git commit -m "chore(i18n): sync sv-SE.json with en.json"
            git push
          else
            echo "No changes to commit."
          fi
